### PR TITLE
Chore/restore 0.22.0 release

### PR DESCRIPTION
**Pull request by alexandraB99**

### CODE REVIEW

**Comment by alexandraB99** [comment]
@noeliaSD I have updated Models.qml as well as DemoApp and main.qml, should be fine now. Please have a look and let me know if you observed anything else, if not we could squash the commits and merge this PR. Thanks for initiating this!

**Review by PascalPrecht — CHANGES_REQUESTED** [review]
Cool, this seems to fix #547 - thanks for that!!

Would be wonderful if we could squash these commits into one, following the commit message conventions.

**Review by noeliaSD — APPROVED** [review]
Squashed commits and ready to merge! Great job @alexandraB99, thank you!!

@PascalPrecht if you don't have any objection, we can now merge it.

**Review by PascalPrecht — APPROVED** [review]
Great great work you two!

**Pull request merged**
