### PR TITLE
feat(StatusListItem): Added new properties to handle inline tags needed in the wallet section

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
feat(StatusListItem): Added new properties to handle inline tags needed in the wallet section

### Checklist

- [x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [ ] add documentation if necessary (new component, new feature)
- [x] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [x] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [x] test changes in [status-desktop](https://github.com/status-im/status-desktop)

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Code-wise this looks straight forward... what I've noticed though, is that we already have a `tagsModel`. I assume it's a different thing otherwise you wouldn't introduce a new thing, but I'm wondering if this is getting a little bit out of hand.

Would it be possible to maybe have only one tagsModel and a flag which specificies whether we have "inline" tags or not?
Do we have cases were we want to render both types of tags at the same time?

**Review by alexandraB99 — CHANGES_REQUESTED** [review]
@Khushboo-dev-cpp could you please create a new list item, `StatusTagListItem` or similar please? this StatusListItem is getting very big with 400 lines of code, thus unmaintainable.

**Comment by Khushboo-dev-cpp** [comment]
> Code-wise this looks straight forward... what I've noticed though, is that we already have a `tagsModel`. I assume it's a different thing otherwise you wouldn't introduce a new thing, but I'm wondering if this is getting a little bit out of hand.
> 
> Would it be possible to maybe have only one tagsModel and a flag which specificies whether we have "inline" tags or not? Do we have cases were we want to render both types of tags at the same time?

Hey @PascalPrecht I had thought of the same solution, I dont have a use case right now where we need both, I could add a flag for isInlineTag and update this :)

**Comment by Khushboo-dev-cpp** [comment]
> @Khushboo-dev-cpp could you please create a new list item, `StatusTagListItem` or similar please? this StatusListItem is getting very big with 400 lines of code, thus unmaintainable.

Hey @alexandraB99 ! I agree this StatusListItem is rather growing rapidly, however should I make this separate already? I think with new design system we will have a clear overview of what a list item will be and we can then decide how to separate them? let me know what you think?

**Review by alexandraB99 — APPROVED** [review]
let's revise when we got the new design system work

**Comment by Khushboo-dev-cpp** [comment]
> > Code-wise this looks straight forward... what I've noticed though, is that we already have a `tagsModel`. I assume it's a different thing otherwise you wouldn't introduce a new thing, but I'm wondering if this is getting a little bit out of hand.
> > Would it be possible to maybe have only one tagsModel and a flag which specificies whether we have "inline" tags or not? Do we have cases were we want to render both types of tags at the same time?
> 
> Hey @PascalPrecht I had thought of the same solution, I don't have a use case right now where we need both, I could add a flag for isInlineTag and update this :)

Hey @PascalPrecht I was looking at adding the flag I remembered why I didn't do it in the first place, its because adding this is making add many if else cases to handle height etc and it doesn't work perfectly. If you do not think its a very inconvenient to the end user I'd like to keep it as it is

**Comment by PascalPrecht** [comment]
@Khushboo-dev-cpp perfectly fine, I was just throwing out ideas :)

**Pull request merged**
