### PR TITLE
feat(StatusInput): exposed letterIconName property

### PR DESCRIPTION
**Pull request by alexandraB99**
Exposed letterIconName to be set in StatusLetterIdenticon

Needed for: https://github.com/status-im/status-desktop/issues/5636

### Checklist

- [x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [x] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [x] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [x] test changes in [status-desktop](https://github.com/status-im/status-desktop)

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Review by osmaczko — COMMENTED** [review]
~~I miss context here. Until now `StatusLetterIdenticon` operated on text, not on the icon. I don't see how it's related to [Adjust text color based on dark/light theme](https://github.com/status-im/status-desktop/issues/5636), could you please clarify?~~

After a second look I think I get it. Property `letterIconName` is misleading a little bit, it sounds as if we have to put there letter icon, e.g. `a.svg`, `b.svg` etc.

`letterIconName` -> `letterIdenticonText` ?

**Review by stefandunca — APPROVED** [review]

**Comment by PascalPrecht** [comment]
Not sure if intentional, but this PR also adds a smiley icon.
According to this commit it shouldn't be.

Was that a mistake?

**Comment by alexandraB99** [comment]
> Not sure if intentional, but this PR also adds a smiley icon. According to this commit it shouldn't be.
> 
> Was that a mistake?

@PascalPrecht which commit? After discussion with John, we stick to the [designs](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2975%3A489237) where we use the smiley to set an emoji to the channel (optionally)

**Comment by PascalPrecht** [comment]
This one of this PR (https://github.com/status-im/StatusQ/pull/671/commits/4d58d35dad141f5d90eea1697ef2a13b4c71fb31) it says it exposes a property, but then it also seems to add an SVG asset, which I didn't expect (according to the commit).

So was wondering if that was by accident.

**Pull request merged**
