### PR TITLE
fix(StatusIcon): flag/currency icons are rendered blurred

### PR DESCRIPTION
**Pull request by caybro**
- set the Image's `sourceSize` only if it's an SVG, otherwise it is
rendered blurry
- remove antialiasing/mipmap; it's not the correct fix, doesn't really
improve the visual quality for smallish items like icons and just causes
memory/GPU overhead

### Screenshots (before/after)
Snímek obrazovky z 2022-07-05 22-35-38
Snímek obrazovky z 2022-07-05 23-08-53

### status-desktop screenshot
Snímek obrazovky z 2022-07-06 11-52-19

### Checklist

- [x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [x] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [x] test changes in [status-desktop](https://github.com/status-im/status-desktop)

### CODE REVIEW

**Comment by caybro** [comment]
> 1. Take a look on the theme `Switch` in the top-right corner of your screenshots. They got broken slightly_frowning_face
>    Not sure if it's because of your changes. But that would make sense.

@igor-sirotin here's your theme switch "icon" :D

```qml
Text {
  text: "🌤"
  font.pixelSize: 15
  anchors.verticalCenter: parent.verticalCenter
}
```

**Comment by caybro** [comment]
> > Hmm, I'll take a look but they seem the same to me? (compare before/after). How should they look like?
> 
> First of all, yes, I should have noted the before/after. It's probably not your changes' consequences. But that's interesting. I'm on latest master ([c4421d3](https://github.com/status-im/StatusQ/commit/c4421d35523db1d1aafac630917eddcd788f185f)), the switch looks like this: imageimage

You're probably usign a different font... what OS?

> > Those flag/currency icons are in PNG, with no `@2x` variant so can't do much more here (yes, this screenshot is taken on a 4k screen)
> 
> Okaay disappointed Should we ask anyone where did we get these icons and try to get the high-res ones?

OK, I'll make a note in the original BR when this gets merged

**Review by MishkaRogachev — APPROVED** [review]

**Comment by caybro** [comment]
For the record, the flags come from this site: https://twemoji.twitter.com/

**Comment by caybro** [comment]
> > For the record, the flags come from this site: https://twemoji.twitter.com/
> 
> Well, if the flags are coming from Twemoji, can't we just use the `svg` for those? We even have them in the assets already.

@igor-sirotin I was curious so I just gave it a quick try in statusq/sandbox and it looks a wee better than the fixed version of PNGs (code stays the same, I just exchanged the model to use SVGs), see here:

Snímek obrazovky z 2022-07-06 13-42-55

**Comment by caybro** [comment]
@igor-sirotin can you actually please give it a test locally on macOS (with this version first), and then eventually if it's still not good enough, I can push the SVG version to see the difference. It's really hard to capture on a screenshot, has to be seen live.

One note though: if we decide to go with SVGs, they are much bigger (in file size), so they are going to use a lot more GPU memory

**Pull request merged**
