### PR TITLE
refactor(sandbox): remove obsolete timeline demo code

### PR DESCRIPTION
**Pull request by alexandraB99**
This feature is deprecated and shall be removed

Relates to #4177

### CODE REVIEW

**Review by PascalPrecht — APPROVED** [review]
LGTM!

Since this is not really a bugfix in StatusQ, it'd be cool if you could change the commit message to something like:

```
refactor(sandbox): remove obsolete timeline demo code
```

**Comment by jrainville** [comment]
> you could change the commit message to something like:

it could be a `chore` even. But anyway, I agree that `fix` isn't the right term.

**Review by jrainville — APPROVED** [review]

**Comment by alexandraB99** [comment]
You are right, updated!

**Comment by PascalPrecht** [comment]
Thank you @alexandraB99 !

**Pull request merged**
