### PR TITLE
feat(StatusDialog): Add background color property to make the dialog background customizable

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
feat(StatusDialog): Add background color property to make the dialog background customizable

### Checklist

- [x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [x] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [x] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [x] test changes in [status-desktop](https://github.com/status-im/status-desktop)

### CODE REVIEW

**Review by osmaczko — CHANGES_REQUESTED** [review]
Please don't add properties to `StatusDialog`, we should keep it as simple as possible to avoid (in the future) big number of API properties and aliases as we do have now for many other components. If a custom color is needed please simply do the following on the client side:
```
background: Rectangle {
    color: yourColor
    radius: 8
}
```
You could also extract `DialogBackground` component to avoid `radius: 8` duplication:
```
background: DialogBackground {
    color: yourColor
}
```
Take a look at similar discussion: https://discord.com/channels/624205794384281629/697843216048717905/999253801347334144

**Comment by Khushboo-dev-cpp** [comment]
makes sense @osmaczko ! will do :)

**Comment by Khushboo-dev-cpp** [comment]
> makes sense @osmaczko ! will do :)

All done, check when you can :) @osmaczko

**Review by osmaczko — APPROVED** [review]
Looks good!

**Pull request merged**
