### PR TITLE
feat: Add universal api for loading indicator

### PR DESCRIPTION
**Pull request by borismelnik**
Closes: #56

### CODE REVIEW

**Comment by PascalPrecht** [comment]
@borismelnik I believe there has been a misunderstanding here.

This commit says it closes #56, but all it does is it renames the `loading` property of some button components. I don't think they have to be renamed, `loading` or `pending` is fine with me.

#56 is about making `StatusRoundImage` capable of showing a loading indicator while the image resource is being loaded.

**Comment by borismelnik** [comment]
> @borismelnik I believe there has been a misunderstanding here.
> 
> This commit says it closes #56, but all it does is it renames the `loading` property of some button components. I don't think they have to be renamed, `loading` or `pending` is fine with me.
> 
> #56 is about making `StatusRoundImage` capable of showing a loading indicator while the image resource is being loaded.

Got it! set `true` if image.state == Loading.

**Comment by PascalPrecht** [comment]
For clarification, I've added another comment to the original issue. Hopefully that clears up the intent:

https://github.com/status-im/StatusQ/issues/56#issuecomment-847810555

**Comment by PascalPrecht** [comment]
This has landed as https://github.com/status-im/StatusQ/commit/44b275f23d2025437914866aa75594965b66d80f

Great job @borismelnik ✨

**Pull request closed without merging**
