### PR TITLE
feat(StatusTagSelector): fixed admin / non admin permissions

### PR DESCRIPTION
**Pull request by alexandraB99**
Needed for: https://github.com/status-im/status-desktop/issues/5941

### Checklist

- [x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [x] add documentation if necessary (new component, new feature)
- [x] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [x] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [x] test changes in [status-desktop](https://github.com/status-im/status-desktop)

### CODE REVIEW

**Comment by alexandraB99** [comment]
Uploading rer.mov…

**Review by noeliaSD — COMMENTED** [review]
As discussed before, I'm not sure if it is necessary to update `StatusQ` since `StatusTagItem` allows to setup a `readonly tag + icon` that is enough to categorize a `status desktop admin`. 
For mi the concept of `admin` is not an abstract one and not necessary to define the api of this general component.

**Comment by PascalPrecht** [comment]
I think I'll have to agree with @noeliaSD here.
A UI component doesn't need to know about a notion of "admin".
Applications should configure the component as needed, whether that is in the context of admin permissions, or something else, should not be business of the UI component.

**Comment by alexandraB99** [comment]
@noeliaSD Updated!

**Comment by alexandraB99** [comment]
all fixed [here](https://github.com/status-im/status-desktop/pull/7188)

**Pull request closed without merging**
