### PR TITLE
fix(StatusQ.Popups): Replace TextEdit to StatusBaseInput for SearchPopup

### PR DESCRIPTION
**Pull request by borismelnik**
Closes: https://github.com/status-im/status-desktop/issues/5059

### Checklist

- [x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [ ] test changes in [status-desktop](https://github.com/status-im/status-desktop)

### CODE REVIEW

**Comment by PascalPrecht** [comment]
@borismelnik I think generally these changes LGTM. Can you update the checklist?

**Comment by PascalPrecht** [comment]
@borismelnik I think generally these changes LGTM. Can you update the checklist?

**Comment by PascalPrecht** [comment]
I realized there are changes in @Khushboo-dev-cpp 's #595 that might be related to your changes as well. It looks like she's created a component to be used in the search popup.

Does this overlap?

**Comment by borismelnik** [comment]
> I realized there are changes in @Khushboo-dev-cpp 's #595 that might be related to your changes as well. It looks like she's created a component to be used in the search popup.
> 
> Does this overlap?

I don't think so. I don't see changes in SearchPopup.

**Comment by PascalPrecht** [comment]
Ah no it's because `StatusInputWithCursor` looks like something that wants to be used in the search popup, but I could be mistaken.

**Comment by Khushboo-dev-cpp** [comment]
I think its different @borismelnik I have attached a video of the StatusInputWithCursor here. maybe that helps? 

https://user-images.githubusercontent.com/60327365/159665494-62a74ac0-d9ef-498b-b8f3-e1289579898b.mov

**Comment by borismelnik** [comment]
@Khushboo-dev-cpp I agreed :)

**Pull request merged**
